name: vita_dl
description: "A PSVita application downloader"
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3+1
  path: ^1.9.0
  url_launcher: ^6.3.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  csv: ^6.0.0
  provider: ^6.1.2
  crypto: ^3.0.5
  xml: ^6.5.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_hooks: ^0.20.5
  flutter_html: 3.0.0-beta.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  background_downloader: ^8.9.4
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  zustand: ^0.0.5
  hive_ce: ^2.10.0
  hive_ce_flutter: ^2.2.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  hive_ce_generator: ^1.8.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/pkg2zip-linux-aarch64/pkg2zip
    - assets/pkg2zip-windows-x64/pkg2zip.exe