name: fnps
description: "Flutter NoPayStation client"
publish_to: 'none'
version: 1.0.1+0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  csv: ^6.0.0
  provider: ^6.1.2
  crypto: ^3.0.5
  xml: ^6.5.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_hooks: ^0.20.5
  flutter_html: 3.0.0-beta.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  zustand: ^0.0.5
  hive_ce: ^2.10.0
  hive_ce_flutter: ^2.2.0
  dio: ^5.8.0+1
  android_x_storage: ^1.0.2
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1
  saf_util: ^0.6.2
  saf_stream: ^0.11.1
  collection: ^1.19.0
  open_dir: ^0.0.2+1
  open_file_manager:
    git:
      url: https://github.com/nini22P/open_file_manager
      ref: main
  spring_bottom_sheet: ^0.0.3
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  hive_ce_generator: ^1.8.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/pkg2zip-windows-x64/pkg2zip.exe